version: "3.8"

services:
  configserver:
    image: usmannaveed13/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    
    networks:
      - microservice-network
  
  eurekaserver:
    image: usmannaveed13/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - microservice-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:  
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/    
      
  accounts:
    image: usmannaveed13/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    
    networks:
      - microservice-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:  
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka   
           
  loans:
    image: usmannaveed13/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
      
    networks:
      - microservice-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:  
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/     
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
         
  cards:
    image: usmannaveed13/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    
    networks:
      - microservice-network
    depends_on:
      - configserver
      - eurekaserver  
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:  
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/  
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
  
networks:
  microservice-network: 